### ISSUE TITLE
Reconnect after disconnecting

### ISSUE THREAD

**Issue by advancedlogic** [nathantsoi/vue-native-websocket#12]
Hi,
is there a way to reconnect the WS after a disconnection (for example after a reboot of the server)?
Thanks

**Comment by nmeylan** [comment]
Hi @advancedlogic I have implemented a strategy to auto reconnect my websocket after a disconnection. It work well, but I'm not proud of my solution. You can find it here https://gist.github.com/nmeylan/ee3f85346aa75907558b8cff9e3ef328

I don't like it because I rely on the current implementation of this lib, and if it changes my code will be broken

However I would like to see a built-in solution. Maybe I will made a pull request for this if I have the time.

Hope this helps you

**Comment by advancedlogic** [comment]
thanks
