### ISSUE TITLE
Reconnect on loss ？？

### ISSUE THREAD

**Issue by taojinbo1990** [nathantsoi/vue-native-websocket#21]
Broken cable is not supported

**Comment by nathantsoi** [comment]
good idea, could you submit a PR?

**Comment by weglov** [comment]
I have created pull request that implements simple reconnect feature: https://github.com/nathantsoi/vue-native-websocket/pull/25

**Comment by Anni619** [comment]
@nathantsoi 
I have the same issue, could you fix it asap?)

**Comment by ThomasKlessen** [comment]
@weglov: I tried your reconnect feature but there is still a problem.

I have some nested views and on the topmost level i use v-if to react on Connection-state.
That means is i lose the connection i show a little error-view.

But therefor vue removes all other prevoiusly existing views and calls beforeDestroy on them.
That means that your reconnect timeout get's deleted. 

I solved this issue for now by just commenting out this line in beforeDestroy function:
clearTimeout(o.reconnectTimeoutId)

But i am not sure what impacts this could have!!!

I think the expected behavior would be to clear the timeout only if it is the last existing Vue Instance?

I would love to get some input on this...
greetz Thomas

**Comment by mrwhy-orig** [comment]
Having the same problem as @ThomasKlessen 
Any improvements here?

**Comment by weglov** [comment]
@ThomasKlessen @mrwhy-orig tnx you are right, fixed: #35
pls check and thumb up

**Comment by Helmi** [comment]
@weglov can confirm your fix works and fixed my problem too. 

@nathantsoi any chance to see this accepted anytime soon?
